language: java
script: ./gradlew build jacocoTestReport

jdk:
  - openjdk8

before_install:
  - sudo pip install codecov

after_success:
  - codecov
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
